In [1]:
import pandas as pd

In [124]:
df = pd.read_csv(r"./data2.csv", encoding="gbk")

In [ ]:
df.query("final_score == 1")

In [125]:
time_value = pd.DatetimeIndex(df["create_time"])

In [79]:
time_value

DatetimeIndex(['2018-11-02 00:01:45', '2018-11-02 00:01:55',
               '2018-11-02 00:03:19', '2018-11-02 00:03:44',
               '2018-11-02 00:04:19', '2018-11-02 00:04:26',
               '2018-11-02 00:07:17', '2018-11-02 00:08:28',
               '2018-11-02 00:08:54', '2018-11-02 00:09:45',
               ...
               '2018-11-15 12:59:17', '2018-11-15 12:59:26',
               '2018-11-15 12:59:36', '2018-11-15 12:59:48',
               '2018-11-15 12:59:57', '2018-11-15 13:00:03',
               '2018-11-15 13:00:04', '2018-11-15 13:00:08',
               '2018-11-15 13:00:14', '2018-11-15 13:00:18'],
              dtype='datetime64[ns]', name='create_time', length=100000, freq=None)

In [80]:
time_value.day

Int64Index([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
            ...
            15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           dtype='int64', name='create_time', length=100000)

In [126]:
df["day"] = time_value.day

In [127]:
df.loc[:, "month"] = time_value.month
df.loc[:, "hour"] = time_value.hour
df.loc[:, "minute"] = time_value.minute

In [65]:
df.groupby("receipt_address").nunique()["receipt_phone"].reset_index().query("receipt_phone > 1")

                            receipt_address  receipt_phone
14                   上海市上海市嘉定区依玛路389弄36号802              2
15                  上海市上海市嘉定区保安路176号上海青浦书画社              2
16                  上海市上海市嘉定区凌云路街道天等路188号A栋              3
42                   上海市上海市嘉定区城中西路448弄1-29号              2
44                        上海市上海市嘉定区塔城东路400号              3
45                       上海市上海市嘉定区塘郁村10队77号              4
52                   上海市上海市嘉定区安亭镇宝中路68号方泰中学              2
53                       上海市上海市嘉定区安亭镇方中路96号              2
63             上海市上海市嘉定区支家路179号近三元路口(税务局后面)              2
79                         上海市上海市嘉定区盈中新村20号              2
80     上海市上海市嘉定区盈浦街道淀山湖大道吾悦广场金街3楼150弄93号307              3
89                         上海市上海市嘉定区长桥二村38号              3
98                          上海市上海市嘉定区龙瑞路46号              2
99                    上海市上海市嘉定区龙腾大道475-477号              2
120         上海市上海市奉贤区南桥镇西韩路228号A3座利施化妆品有限公司              2
124           上海市上海市奉贤区嘉川路245号3号楼606室(近天等路)              2
131       上海市上海市奉贤区外青松公路7166号(近G50高速青浦城区出口)              3
149                        上海市上海市奉贤区海泉路100号              2
159                       上海市上海市奉贤区罗香路星罗苑南门              2
173                        上海市上海市奉贤区长桥二村41号              3
174                  上海市上海市奉贤区长桥二村65号罗香路42号              2
177                        上海市上海市奉贤区长桥四村34号              2
181                 上海市上海市奉贤区长桥街道龙川路罗秀三村48号              2
183                   上海市上海市奉贤区青安路579号(盈港路)              2
184                      上海市上海市奉贤区青昆路南太路31号              3
214                       上海市上海市宝山区北淀浦河路37号              2
232                     上海市上海市宝山区大场镇真大路309号              2
259                        上海市上海市宝山区庆华新村23号              3
260            上海市上海市宝山区庆华新村8号(上海桥梓湾购物中心东北)              2
262                       上海市上海市宝山区救护大队路52号              3
...                                     ...            ...
49094                        陕西省西安市阎良区乾龙物流园              2
49095                        陕西省西安市阎良区兰家村1号              4
49096              陕西省西安市阎良区华南城五金B区5街7栋2-4号              3
49098                      陕西省西安市阎良区杏园小学斜对面              3
49106             陕西省西安市阎良区港务西路华南城A区6街2栋13号              2
49108          陕西省西安市阎良区西安国际港务区华南城B区2街2栋21号              3
49109                陕西省西安市阎良区西安国际港务区港务大道6号              2
49111              陕西省西安市阎良区谢一北三环华南城2号交易广场J              3
49117                        陕西省西安市雁塔区东三爻小学              2
49133              陕西省西安市雁塔区华南城机电E1区16街1栋3楼              4
49172              陕西省西安市雁塔区新筑街道杏渭路碑林驾校训练场东              2
49244                     陕西省西安市雁塔区西安·华南城2区              2
49260                陕西省西安市雁塔区长安西路铭城16号小区门口              2
49278                          陕西省西安市雁塔区雁塔区              3
49306         陕西省西安市雁塔区鱼化寨街道云水一路西安环普产业园中软国际              2
49311     陕西省西安市高陵区210国道西50米老杨家泡馍(耿镇人民政府西北)              2
49314                陕西省西安市高陵区华南城五金B区2街3栋2号              3
49317              陕西省西安市高陵区国际港务区华南城E1区5街1栋              2
49321              陕西省西安市高陵区新寺遗址公园西北(港务西路东)              2
49323            陕西省西安市高陵区新筑街道华南城五金机电B区6街6栋              3
49324                  陕西省西安市高陵区新筑街道杏渭路杏园小学              2
49330               陕西省西安市高陵区港兴路华南城五金B区6街4栋              3
49331               陕西省西安市高陵区港务区华南城B区5街3栋1号              3
49332         陕西省西安市高陵区港务大道8号华盛奥特莱斯购物中心东区1层              3
49333              陕西省西安市高陵区港务大道物联网产业园办公楼4层              2
49334         陕西省西安市高陵区港务西路国际港务区E1区16街1栋34号              3
49338              陕西省西安市高陵区西安华南城E1区10街3栋6号              2
49343             陕西省西安市高陵区陆港大厦(西安市第六十四中学南)              3
49395                 黑龙江省哈尔滨市南岗区哈西街道学府路52号              5
49401                     黑龙江省哈尔滨市南岗区嵩山路31号              2

[5318 rows x 2 columns]

In [70]:
df.query("final_score > 2").index.values

array([    1,     2,     3, ..., 99995, 99996, 99999], dtype=int64)

In [75]:
df.index.isin(df.query("final_score > 2").index.values)

array([False,  True,  True, ..., False, False,  True])

In [158]:
df_new = df[["month", "day", "hour", "minute", "final_score"]]

In [159]:
df_new

       month  day  hour  minute  final_score
0         11    2     0       1            0
1         11    2     0       1            3
2         11    2     0       3            3
3         11    2     0       3            3
4         11    2     0       4            3
5         11    2     0       4            3
6         11    2     0       7            0
7         11    2     0       8            0
8         11    2     0       8            3
9         11    2     0       9            3
10        11    2     0      11            3
11        11    2     0      11            0
12        11    2     0      12            3
13        11    2     0      14            0
14        11    2     0      14            3
15        11    2     0      14            1
16        11    2     0      15            3
17        11    2     0      15            3
18        11    2     0      18            3
19        11    2     0      21            3
20        11    2     0      21            0
21        11    2     0      22            0
22        11    2     0      22            3
23        11    2     0      24            0
24        11    2     0      26            4
25        11    2     0      40            3
26        11    2     0      41            3
27        11    2     0      41            2
28        11    2     0      41            3
29        11    2     0      42            0
...      ...  ...   ...     ...          ...
99970     11   15    12      55            0
99971     11   15    12      56            0
99972     11   15    12      56            3
99973     11   15    12      56            2
99974     11   15    12      56            3
99975     11   15    12      56            3
99976     11   15    12      56            3
99977     11   15    12      56            1
99978     11   15    12      56            3
99979     11   15    12      56            3
99980     11   15    12      57            3
99981     11   15    12      57            3
99982     11   15    12      57            3
99983     11   15    12      57            3
99984     11   15    12      57            3
99985     11   15    12      57            4
99986     11   15    12      58            3
99987     11   15    12      58            1
99988     11   15    12      58            3
99989     11   15    12      58            3
99990     11   15    12      59            0
99991     11   15    12      59            3
99992     11   15    12      59            0
99993     11   15    12      59            0
99994     11   15    12      59            0
99995     11   15    13       0            3
99996     11   15    13       0            3
99997     11   15    13       0            0
99998     11   15    13       0            0
99999     11   15    13       0            3

[100000 rows x 5 columns]

In [130]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [160]:
df_final = df_new

In [161]:
data = df_final[["month", "day", "hour", "minute"]]
target = df_final["final_score"]

In [162]:
data_train, data_test, target_train, target_test = train_test_split(data, target)

In [163]:
ss = StandardScaler()
data_train = ss.fit_transform(data_train)
data_test = ss.transform(data_test)

k = KNeighborsClassifier()
neighbor_dict = {"n_neighbors": [3, 4, 5, 6, 7, 8, 9, 10]}
gs = GridSearchCV(k, param_grid=neighbor_dict, cv=30)
gs.fit(data_train, target_train)
target_predict = gs.predict(data_test)
print("最佳参数")
print(gs.best_params_)
print("最佳结果")
print(gs.best_score_)
print("最佳预估器")
print(gs.best_estimator_)
print("交叉验证结果")
print(gs.cv_results_)

d:\program files\python\python37\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
d:\program files\python\python37\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
d:\program files\python\python37\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until

最佳参数
{'n_neighbors': 10}
最佳结果
0.5916933333333333
最佳预估器
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform')
交叉验证结果
{'mean_fit_time': array([0.24226824, 0.28191085, 0.29662958, 0.33641143, 0.2950525 ,
       0.29254289, 0.28263229, 0.23840038]), 'std_fit_time': array([0.02234652, 0.05483303, 0.0433381 , 0.07274896, 0.03861326,
       0.02082466, 0.03888169, 0.02256875]), 'mean_score_time': array([0.1527445 , 0.18717319, 0.19756118, 0.23235247, 0.20268543,
       0.20557516, 0.19584524, 0.16257863]), 'std_score_time': array([0.01058775, 0.04678413, 0.03091159, 0.0617961 , 0.02000868,
       0.02629515, 0.02780971, 0.01948548]), 'param_n_neighbors': masked_array(data=[3, 4, 5, 6, 7, 8, 9, 10],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 3}, {'n_neighbors': 4}, {'n_neighbors': 5}, {'n_neighbors': 6}, {'n_neighbors': 7}, {'n_neighbors': 8}, {'n_neighbors': 9}, {'n_neighbors': 10}], 'split0_test_score': array([0.52276358, 0.52675719, 0.54313099, 0.55511182, 0.56988818,
       0.58027157, 0.58666134, 0.58746006]), 'split1_test_score': array([0.54113419, 0.54592652, 0.56269968, 0.56309904, 0.58226837,
       0.58666134, 0.5922524 , 0.59265176]), 'split2_test_score': array([0.54414702, 0.54654415, 0.55852976, 0.57171394, 0.57650819,
       0.58849381, 0.58969237, 0.58929285]), 'split3_test_score': array([0.53735517, 0.54614463, 0.56372353, 0.5669197 , 0.59129045,
       0.59168997, 0.59968038, 0.60207751]), 'split4_test_score': array([0.54574511, 0.54894127, 0.56292449, 0.57570915, 0.57650819,
       0.58769477, 0.59688374, 0.60167799]), 'split5_test_score': array([0.53895326, 0.52696764, 0.56012785, 0.56532161, 0.58010388,
       0.57491011, 0.5940871 , 0.59768278]), 'split6_test_score': array([0.52139144, 0.52578968, 0.55177929, 0.55257897, 0.57057177,
       0.57297081, 0.58456617, 0.58296681]), 'split7_test_score': array([0.5289884 , 0.53738505, 0.55057977, 0.56617353, 0.57177129,
       0.57616953, 0.58096761, 0.59016393]), 'split8_test_score': array([0.51979208, 0.52858856, 0.55577769, 0.55537785, 0.57297081,
       0.57257097, 0.58456617, 0.58296681]), 'split9_test_score': array([0.55937625, 0.55737705, 0.57257097, 0.57616953, 0.59096361,
       0.58816473, 0.58976409, 0.59136345]), 'split10_test_score': array([0.53058776, 0.54298281, 0.55897641, 0.57257097, 0.57616953,
       0.58856457, 0.59016393, 0.59256297]), 'split11_test_score': array([0.552 , 0.554 , 0.5676, 0.5792, 0.6   , 0.5912, 0.5988, 0.5968]), 'split12_test_score': array([0.5492, 0.5504, 0.56  , 0.5672, 0.5844, 0.5824, 0.594 , 0.598 ]), 'split13_test_score': array([0.5452, 0.5452, 0.56  , 0.578 , 0.5852, 0.584 , 0.5936, 0.592 ]), 'split14_test_score': array([0.5404, 0.5416, 0.5708, 0.5848, 0.5892, 0.592 , 0.604 , 0.6052]), 'split15_test_score': array([0.532 , 0.5308, 0.566 , 0.5624, 0.5768, 0.5712, 0.5764, 0.576 ]), 'split16_test_score': array([0.5408, 0.5488, 0.5684, 0.5748, 0.5856, 0.5768, 0.5868, 0.5892]), 'split17_test_score': array([0.53621449, 0.53741497, 0.54981993, 0.56942777, 0.57863145,
       0.56782713, 0.58103241, 0.57703081]), 'split18_test_score': array([0.54283427, 0.54443555, 0.55884708, 0.56765412, 0.57646117,
       0.58566853, 0.59007206, 0.59447558]), 'split19_test_score': array([0.53402722, 0.52682146, 0.54883907, 0.56084868, 0.57245797,
       0.57365893, 0.58406725, 0.58446757]), 'split20_test_score': array([0.53042434, 0.5316253 , 0.55684548, 0.56084868, 0.58726982,
       0.58326661, 0.60208167, 0.60008006]), 'split21_test_score': array([0.53082466, 0.52682146, 0.55884708, 0.57445957, 0.58446757,
       0.58206565, 0.5908727 , 0.58847078]), 'split22_test_score': array([0.54443555, 0.54843875, 0.57125701, 0.58046437, 0.59727782,
       0.58526821, 0.60128102, 0.59807846]), 'split23_test_score': array([0.53963171, 0.55644516, 0.55804644, 0.56965572, 0.57646117,
       0.58486789, 0.59727782, 0.60248199]), 'split24_test_score': array([0.55044035, 0.54603683, 0.56164932, 0.57686149, 0.57325861,
       0.57125701, 0.58246597, 0.57726181]), 'split25_test_score': array([0.53322658, 0.5336269 , 0.56164932, 0.57045637, 0.58206565,
       0.58726982, 0.59007206, 0.59167334]), 'split26_test_score': array([0.54283427, 0.54643715, 0.56485188, 0.57125701, 0.57766213,
       0.58286629, 0.58767014, 0.5948759 ]), 'split27_test_score': array([0.54683747, 0.54483587, 0.57606085, 0.57485989, 0.59007206,
       0.57806245, 0.58726982, 0.58726982]), 'split28_test_score': array([0.55164131, 0.54403523, 0.56765412, 0.57245797, 0.58406725,
       0.58606886, 0.59047238, 0.59367494]), 'split29_test_score': array([0.53602882, 0.55404323, 0.58206565, 0.56845476, 0.58126501,
       0.57726181, 0.5928743 , 0.5928743 ]), 'mean_test_score': array([0.53897333, 0.54150667, 0.56166667, 0.56949333, 0.58138667,
       0.58170667, 0.59068   , 0.59169333]), 'std_test_score': array([0.00931081, 0.00959064, 0.00826794, 0.00762803, 0.0076267 ,
       0.00673759, 0.00663114, 0.00748414]), 'rank_test_score': array([8, 7, 6, 5, 4, 3, 2, 1]), 'split0_train_score': array([0.60815769, 0.61094405, 0.62839329, 0.62832432, 0.63810417,
       0.63911112, 0.64352516, 0.64158023]), 'split1_train_score': array([0.60502648, 0.6117303 , 0.62802086, 0.63135897, 0.63677996,
       0.63831108, 0.6405043 , 0.64090433]), 'split2_train_score': array([0.60563885, 0.60987351, 0.62606729, 0.62885361, 0.63690911,
       0.63885402, 0.64119895, 0.64136447]), 'split3_train_score': array([0.60399741, 0.61234258, 0.63064679, 0.63086748, 0.63787467,
       0.63686773, 0.64050926, 0.64126791]), 'split4_train_score': array([0.60413534, 0.61094942, 0.62805357, 0.63035712, 0.63779191,
       0.63834366, 0.64030236, 0.64159896]), 'split5_train_score': array([0.60559747, 0.61132185, 0.62877085, 0.63136406, 0.637585  ,
       0.63754362, 0.64112998, 0.64060582]), 'split6_train_score': array([0.60741527, 0.60918082, 0.62845005, 0.63269838, 0.63791225,
       0.63948468, 0.64242265, 0.64127781]), 'split7_train_score': array([0.60312556, 0.60691872, 0.62584312, 0.62742934, 0.63621567,
       0.63736052, 0.64142954, 0.64062953]), 'split8_train_score': array([0.60301521, 0.60964979, 0.62662933, 0.63016042, 0.63860191,
       0.63733293, 0.64120884, 0.64060194]), 'split9_train_score': array([0.60867046, 0.61028428, 0.63126388, 0.63112595, 0.63886398,
       0.63907088, 0.64163644, 0.64072608]), 'split10_train_score': array([0.60956703, 0.61247741, 0.63054663, 0.63365012, 0.64176058,
       0.64051918, 0.64163644, 0.64278128]), 'split11_train_score': array([0.61097931, 0.61413793, 0.6305931 , 0.63477241, 0.64002759,
       0.63903448, 0.64190345, 0.64216552]), 'split12_train_score': array([0.61001379, 0.61108966, 0.62766897, 0.62998621, 0.63828966,
       0.63721379, 0.64104828, 0.64191724]), 'split13_train_score': array([0.60765517, 0.6098069 , 0.62834483, 0.63227586, 0.64082759,
       0.6393931 , 0.64308966, 0.64266207]), 'split14_train_score': array([0.60583448, 0.61093793, 0.62768276, 0.62845517, 0.63747586,
       0.63823448, 0.64026207, 0.64067586]), 'split15_train_score': array([0.60597241, 0.61237241, 0.63168276, 0.63158621, 0.64009655,
       0.63955862, 0.6418069 , 0.64122759]), 'split16_train_score': array([0.60808276, 0.61308966, 0.63107586, 0.63048276, 0.64088276,
       0.63873103, 0.64329655, 0.64217931]), 'split17_train_score': array([0.61181225, 0.61469497, 0.62850168, 0.6313706 , 0.64039117,
       0.63808775, 0.64114978, 0.64142564]), 'split18_train_score': array([0.61013489, 0.6122038 , 0.62820336, 0.63057571, 0.63985821,
       0.63894789, 0.64075474, 0.6410168 ]), 'split19_train_score': array([0.60726601, 0.6086039 , 0.62791371, 0.63195498, 0.63995476,
       0.63791344, 0.64315467, 0.6434719 ]), 'split20_train_score': array([0.60882458, 0.61272792, 0.63036882, 0.63309978, 0.63929271,
       0.63737552, 0.64212022, 0.6406444 ]), 'split21_train_score': array([0.6097349 , 0.61099004, 0.63064467, 0.63238255, 0.64018924,
       0.63995476, 0.64129265, 0.64206505]), 'split22_train_score': array([0.60634189, 0.61187278, 0.62704477, 0.63167913, 0.63718242,
       0.63661692, 0.64187195, 0.64170644]), 'split23_train_score': array([0.6006455 , 0.61337618, 0.62601032, 0.63129293, 0.63776172,
       0.63803757, 0.64072715, 0.6419547 ]), 'split24_train_score': array([0.61079694, 0.61468649, 0.62854818, 0.63238255, 0.63889272,
       0.64003752, 0.64203746, 0.64170644]), 'split25_train_score': array([0.60697636, 0.60950043, 0.62827232, 0.63076881, 0.63850652,
       0.63650658, 0.63923754, 0.6406306 ]), 'split26_train_score': array([0.6097487 , 0.61172106, 0.62843784, 0.63098949, 0.63954098,
       0.63956856, 0.64301674, 0.64359604]), 'split27_train_score': array([0.60882458, 0.6123969 , 0.62933436, 0.63252048, 0.64010648,
       0.63796861, 0.64162368, 0.64203746]), 'split28_train_score': array([0.61045213, 0.6139141 , 0.62999641, 0.63107225, 0.64012027,
       0.63818929, 0.64129265, 0.64023061]), 'split29_train_score': array([0.60696257, 0.61219001, 0.62878265, 0.62974814, 0.63951339,
       0.63802378, 0.64061681, 0.64174781]), 'mean_train_score': array([0.6073802 , 0.61153286, 0.62872643, 0.63111953, 0.63891033,
       0.63840644, 0.6415269 , 0.64154666]), 'std_train_score': array([0.00266592, 0.00178576, 0.00157409, 0.00156342, 0.0013724 ,
       0.00103006, 0.00099275, 0.00083258])}